# Generated by Django 4.1.5 on 2023-04-11 05:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
        ('home', '0001_initial'),
        ('customer', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('payment_type', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.product')),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
    ]
