# Generated by Django 4.1.5 on 2023-04-10 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=30)),
                ('type', models.CharField(max_length=200)),
                ('style', models.CharField(default='', max_length=200)),
                ('p_name', models.CharField(max_length=50)),
                ('p_number', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('p_stock', models.BigIntegerField()),
                ('p_price', models.FloatField()),
                ('p_image', models.ImageField(upload_to='product/')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.category')),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.type')),
            ],
            options={
                'db_table': 'style',
            },
        ),
    ]
