# Generated by Django 4.1.5 on 2023-04-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='customer')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=25)),
                ('e_mail', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=20)),
                ('e_mail', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='seller/')),
                ('bank_name', models.CharField(max_length=150)),
                ('acc_name', models.CharField(max_length=150)),
                ('accc_no', models.BigIntegerField()),
                ('ifsc', models.CharField(max_length=150)),
                ('branch_name', models.CharField(max_length=500)),
                ('Username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'seller',
            },
        ),
    ]
